kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    component: acm-cli-downloads
  name: acm-cli-downloads
spec:
  replicas: 1
  selector:
    matchLabels:
      component: acm-cli-downloads
  template:
    metadata:
      labels:
        component: acm-cli-downloads
    spec:
      containers:
        - name: acm-cli-downloads
          args:
          - "--secure={{ .Values.isOpenshift }}"
          image: quay.io/stolostron/acm-cli:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              port: downloads
              scheme: "HTTP{{ if .Values.isOpenshift }}S{{ end }}"
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: downloads
              scheme: "HTTP{{ if .Values.isOpenshift }}S{{ end }}"
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          ports:
      {{- if not .Values.isOpenshift }}
            - containerPort: 8080
              name: downloads
              protocol: TCP
      {{- else }}
            - containerPort: 8443
              name: downloads
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/run/acm-cli-cert"
              name: acm-cli-cert
              readOnly: true
      volumes:
        - name: acm-cli-cert
          secret:
            secretName: acm-cli-cert
      {{- end }}
      automountServiceAccountToken: false
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - console
                - key: component
                  operator: In
                  values:
                  - console
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - console
                - key: component
                  operator: In
                  values:
                  - console
